// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyRIoHvc6DYet_38y7OU9dbl8nlmq8QhY',
    appId: '1:125324024672:web:142711cbea4da18be21c05',
    messagingSenderId: '125324024672',
    projectId: 'misk-edu-and-welfare-trust',
    authDomain: 'misk-edu-and-welfare-trust.firebaseapp.com',
    storageBucket: 'misk-edu-and-welfare-trust.firebasestorage.app',
    measurementId: 'G-SWGM1EKYHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJbMGjDfceY78ukuptBbssLNHZJn13kg',
    appId: '1:125324024672:android:b2f3667f0636880fe21c05',
    messagingSenderId: '125324024672',
    projectId: 'misk-edu-and-welfare-trust',
    storageBucket: 'misk-edu-and-welfare-trust.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNKaSjQbiWwRA8z0ploqEWIM1nvnVJjyU',
    appId: '1:125324024672:ios:f98cdcc854bd35a8e21c05',
    messagingSenderId: '125324024672',
    projectId: 'misk-edu-and-welfare-trust',
    storageBucket: 'misk-edu-and-welfare-trust.firebasestorage.app',
    iosBundleId: 'com.miskewt.miskEwtErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNKaSjQbiWwRA8z0ploqEWIM1nvnVJjyU',
    appId: '1:125324024672:ios:f98cdcc854bd35a8e21c05',
    messagingSenderId: '125324024672',
    projectId: 'misk-edu-and-welfare-trust',
    storageBucket: 'misk-edu-and-welfare-trust.firebasestorage.app',
    iosBundleId: 'com.miskewt.miskEwtErp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyRIoHvc6DYet_38y7OU9dbl8nlmq8QhY',
    appId: '1:125324024672:web:f36de2abf9a36843e21c05',
    messagingSenderId: '125324024672',
    projectId: 'misk-edu-and-welfare-trust',
    authDomain: 'misk-edu-and-welfare-trust.firebaseapp.com',
    storageBucket: 'misk-edu-and-welfare-trust.firebasestorage.app',
    measurementId: 'G-PRB8WVKVPT',
  );

}